Quiz/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls'))

]

Quiz/polls/urls.py
from django.urls import path
from django.conf.urls import url

from . import views
from polls.views import HomeView, CreateTournamentView, LoginView, SignUpView, TournamentView, LogoutView, HighscoresView, ResultsView

app_name = 'polls'
urlpatterns = [
    path('tournament/<int:tournament_id>/', TournamentView.as_view(), name='tournament'),
    path('', TournamentView.as_view(), name='check_answer'),
    path('create/', CreateTournamentView.as_view(), name='create'),
    path('create_tourny/', CreateTournamentView.as_view(), name='create_tourny'),
    path('index/', HomeView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('highscores/', HighscoresView.as_view(), name='highscores'),
    path('', SignUpView.as_view(), name='create_user'),
    path('scores/<int:score>', ResultsView.as_view(), name='results'),
]

Quiz/polls/models.py
from django.db import models


class Tournament(models.Model):
    DIFFICULTY = (
        ('E', 'Easy'),
        ('M', 'Medium'),
        ('H', 'Hard'),
    )

    name = models.CharField(
        max_length=100,
        default='')

    start_date = models.DateField()

    end_date = models.DateField()

    category = models.CharField(
        max_length=200,
        default='Any Category')

    difficulty = models.CharField(
        max_length=100,
        choices=DIFFICULTY,
        default='Easy')


class Question(models.Model):
    tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    correct_ans = models.CharField(max_length=200)


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=200)


class Player_Scores(models.Model):
    username = models.CharField(max_length=200)
    tournament = models.IntegerField()
    current_question = models.IntegerField()
    score = models.IntegerField()

Quiz/polls/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.urls import reverse
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth import (authenticate, login, logout, )
from django.views.generic import View
from django.http import HttpResponseRedirect
import json
import datetime
from django.contrib import messages
import requests

from .models import Tournament, Question, Answer, Player_Scores

categories = {}


class HomeView(View):
    @method_decorator(login_required)
    def get(self, request):
        current_date = datetime.date.today()
        active = Tournament.objects.filter(start_date__lte=current_date, end_date__gte=current_date)
        upcoming = Tournament.objects.filter(start_date__gt=current_date)

        return render(request, 'polls/index.html', {'active': active, 'upcoming': upcoming})


super = user_passes_test(lambda u: u.is_superuser)


class CreateTournamentView(View):
    @method_decorator(super)
    def get(self, request):
        response = requests.get('https://opentdb.com/api_category.php')
        data = json.loads(response.content)
        for cat in data['trivia_categories']:
            categories["%d" % cat["id"]] = cat['name']
        return render(request, 'polls/create_tourny.html', {'categories': categories})

    @method_decorator(super)
    def post(self, request):
        name = request.POST.get('name')
        start_date = request.POST.get('start_date')
        end_date = request.POST.get('end_date')
        difficulty = request.POST.get('difficulty').lower()
        category = request.POST.get('category')

        response = requests.get(
            'https://opentdb.com/api.php?amount=10&category=%s&difficulty=%s' % (category, difficulty))
        data = json.loads(response.content)
        if data['response_code'] == 0:
            tournament = Tournament.objects.create(name=name, start_date=start_date, end_date=end_date,
                                                   difficulty=difficulty, category=categories.get("%s" % category))
            tournament.save()
            for q in data['results']:
                question = Question.objects.create(tournament=tournament, question_text=q["question"],
                                                   correct_ans=q["correct_answer"])
                answer = Answer.objects.create(question=question, answer_text=q["correct_answer"])
                answer.save()
                for ans in q["incorrect_answers"]:
                    answer = Answer.objects.create(question=question, answer_text=ans)
                    answer.save()
        current_date = datetime.date.today()
        active = Tournament.objects.filter(start_date__lte=current_date, end_date__gte=current_date)
        upcoming = Tournament.objects.filter(start_date__gt=current_date)
        return render(request, 'polls/index.html', {'active': active, 'upcoming': upcoming})


class LoginView(View):
    def get(self, request):
        return render(request, 'polls/login.html')

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('polls:index'))
        else:
            return render(request, 'polls/login.html')


class SignUpView(View):
    def get(self, request):
        return render(request, 'polls/signup.html', {})

    def post(self, request):
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        if username != "" and password != "" and email != '':
            user = User.objects.create_user(first_name='', last_name='', email='', username=username, password=password)
            user.save()
            return HttpResponseRedirect(reverse('polls:login'))
        else:
            return render(request, 'polls/signup.html')


class LogoutView(View):
    @method_decorator(login_required)
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('polls:login'))


class TournamentView(View):
    @method_decorator(login_required)
    def get(self, request, tournament_id):

        current_tournament = Tournament.objects.get(id=tournament_id)

        if Player_Scores.objects.filter(username=request.user.username, tournament=tournament_id).count() < 1:
            new_entry = Player_Scores.objects.create(username=request.user.username, tournament=tournament_id,
                                                     current_question=0, score=0)
            new_entry.save()
        current_user = Player_Scores.objects.get(username=request.user.username, tournament=tournament_id)

        if current_user.current_question < 10:
            questions = Question.objects.filter(tournament=tournament_id).order_by('id')
            question = questions[current_user.current_question]
            answers = Answer.objects.filter(question=question).order_by('?')

            return render(request, 'polls/tournament.html',
                          {'tournament': current_tournament, 'question': question, "answers": answers,
                           'question_num': current_user.current_question + 1})
        else:
            return HttpResponseRedirect(reverse('polls:results', kwargs={"score": current_user.score}))

    @method_decorator(login_required)
    def post(self, request):
        current_user = Player_Scores.objects.get(username=request.user.username,
                                                 tournament=request.POST.get("tournament_id"))
        questions = Question.objects.filter(tournament=request.POST.get("tournament_id")).order_by('id')
        question = questions[current_user.current_question]
        question_num = str(current_user.current_question + 1)

        if request.POST.get("answers") == question.correct_ans:
            current_user.score += 1
            messages.success(request, 'You got question %s: Correct!' % question_num)
        else:
            messages.error(request, 'You got question %s: Incorrect' % question_num)
        current_user.current_question += 1
        current_user.save()

        return HttpResponseRedirect(
            reverse('polls:tournament', kwargs={"tournament_id": request.POST.get("tournament_id")}))


class HighscoresView(View):
    def get(self, request):
        high_scores = []
        all_scores = Player_Scores.objects.filter(current_question=10)
        for s in all_scores:
            filtered_scores = Player_Scores.objects.filter(tournament=s.tournament).order_by('-score')
            high_scores.append(filtered_scores[0])
        scores = list(set(high_scores))
        tournaments = Tournament.objects.all()
        return render(request, 'polls/highscores.html', {"highscores": scores, "tournaments": tournaments})


class ResultsView(View):
    @method_decorator(login_required)
    def get(self, request, score):
        return render(request, 'polls/results.html', {"score": score})

Quiz/templates/polls/create_tourny.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% block content %}
<nav class="navbar navbar-dark bg-dark">
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="/polls/index">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/create">Create Tournament</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/highscores">Highscores</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/logout">Logout</a>
  </li>
</ul>
</nav>
<div class="container">
<form method="POST" action="{% url 'polls:create_tourny' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="name">Enter tournament name:</label>
        <input type="text" id="name" name="name" class="form-control" placeholder="Name"><br>

        <label for="sdate">Start date:</label>
        <input id="sdate" name="start_date" class="form-control" placeholder="MM/DD/YYY" type="date"><br>

        <label for="edate">End date:</label>
        <input id="edate" name="end_date" class="form-control" placeholder="MM/DD/YYY" type="date"><br>

        <label for="diff">Select a difficulty:</label>
        <select class="form-control" id="diff" name="difficulty">
            <option value="Easy">Easy</option>
            <option value="Medium">Medium</option>
            <option value="Hard">Hard</option>
        </select><br>

        <label for="cat">Select a category list (select one):</label>
        <select class="form-control" id="cat" name="category">
            {% for key, cat in categories.items %}
                <option value={{ key }}>{{ cat }}</option>
            {% endfor %}
        </select>
    </div>

    <button class="btn btn-primary create" type="submit" value="Create">Create</button>
</form>
</div>
{% endblock %}

Quiz/templates/polls/highscores.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% block content %}
<nav class="navbar navbar-dark bg-dark">
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="/polls/index">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/create">Create Tournament</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/highscores">Highscores</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/logout">Logout</a>
  </li>
</ul>
</nav>
<div class="container">

<table class="table">
  <thead>
    <tr>
      <th scope="col">User Name</th>
      <th scope="col">Tournament</th>
      <th scope="col">Score</th>
    </tr>
  </thead>
  <tbody>
    {% for score in highscores %}
        <tr>
          <td>{{ score.username }}</td>
          {% for t in tournaments %}
              {% if t.id == score.tournament %}
                <td>{{ t.name }}</td>
              {% endif %}
          {% endfor %}
          <td>{{ score.score }}</td>
        </tr>
    {% endfor %}
  </tbody>
</table>

</div>
</div>
{% endblock %}

Quiz/templates/polls/index.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% block content %}
<nav class="navbar navbar-dark bg-dark">
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="/polls/index">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/create">Create Tournament</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/highscores">Highscores</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/logout">Logout</a>
  </li>
</ul>
</nav>
<div class="container">
<h2>Active Tournaments</h2>
<div class="row">
  {% for t in active %}
    <div class="col-sm-6">
        <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{t.name}}</h5>
          <p class="card-text">Start date: {{t.start_date}}</p>
          <p class="card-text">Category: {{t.category}}</p>
          <p class="card-text">End date: {{t.end_date}}</p>
          <p class="card-text">Difficulty: {{t.difficulty}}</p>
        <a href="/polls/tournament/{{t.id}}" class="btn btn-primary">Enter Tournament</a>
      </div>
    </div>
    </div>
  {% endfor %}
</div>
<br>
<h2>Upcoming Tournaments</h2>
<div class="row">
  {% for t in upcoming %}
    <div class="col-sm-6">
        <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{t.name}}</h5>
          <p class="card-text">Start date: {{t.start_date}}</p>
          <p class="card-text">Category: {{t.category}}</p>
          <p class="card-text">End date: {{t.end_date}}</p>
          <p class="card-text">Difficulty: {{t.difficulty}}</p>
        <a href="/polls/tournament/{{t.id}}" class="btn btn-primary disabled">Enter Tournament</a>
      </div>
    </div>
    </div>
  {% endfor %}
</div>
</div>
{% endblock %}

Quiz/templates/polls/login.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% block content %}
<nav class="navbar navbar-dark bg-dark">
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="/polls/index">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/create">Create Tournament</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/logout">Logout</a>
  </li>
</ul>
</nav>
<div class="container login">
<form method="POST" action="{% url 'polls:login' %}">
    {% csrf_token %}
    <div class="form-group row">
      <label for="username" class="col-sm-2 col-form-label">Username</label>
      <div class="col-sm-10">
        <input type="text" id="username" class="form-control" name="username" placeholder="Username">
      </div>
    </div>
    <div class="form-group row">
      <label for="password" class="col-sm-2 col-form-label">Password</label>
      <div class="col-sm-10">
        <input type="text" id="password" class="form-control" name="password" placeholder="Password">
      </div>
    </div>

    <button class="btn btn-primary login" type="submit" value="login">Login</button><br>
    <a class="btn btn-primary login"  href="/polls/signup">Sign Up</a>
</form>
</div>
{% endblock %}

Quiz/templates/polls/results.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% block content %}
<nav class="navbar navbar-dark bg-dark">
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="/polls/index">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/create">Create Tournament</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/highscores">Highscores</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/logout">Logout</a>
  </li>
</ul>
</nav>
<div class="container">
    <h1>You scored {{ score }} out of 10</h1>
</div>
</div>
{% endblock %}

Quiz/templates/polls/signup.html
{% load static %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% block content %}
<nav class="navbar navbar-dark bg-dark">
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="/polls/index">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/create">Create Tournament</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/logout">Logout</a>
  </li>
</ul>
</nav>
<div class="container">
<form method="POST" action="{% url 'polls:signup' %}">
    {% csrf_token %}
    <label for="name">Username:</label>
    <input type="text" id="name" name="username" class="form-control" placeholder="Username">
        <label for="mail">Email:</label>
            <input type="text" id="mail" name="email" class="form-control" placeholder="Email">

    <label for="pass">Password:</label>
    <input type="password" id="pass" name="password" class="form-control" placeholder="Password">
    <br>
    <button class="btn btn-primary" type="submit" value="login">Sign Up</button>
</form>
</div>
{% endblock %}

Quiz/templates/polls/tournament.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% block content %}
<nav class="navbar navbar-dark bg-dark">
<ul class="nav">
  <li class="nav-item">
    <a class="nav-link active" href="/polls/index">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/create">Create Quiz</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/highscores">Highscore</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/polls/logout">Logout</a>
  </li>
</ul>
</nav>
<div class="container">
<h1 class="tournament_title">{{tournament.name}}</h1><br>
<h2>Queston {{question_num}}:</h2>
<h3 class="question">{{ question.question_text|safe }}</h3>
<form method="POST" action="{% url 'polls:check_answer' %}">
    {% csrf_token %}
    {% for a in answers %}
        <input type="radio" class="radio" name="answers" value="{{ a.answer_text }}">{{ a.answer_text|safe }}<br>
    {% endfor %}
    <br>
    <button class="btn btn-primary login" type="submit" value="checkans">Check Answer</button>
    <input type="hidden" name="tournament_id" value="{{ tournament.id }}">
    <input type="hidden" name="question" value="{{ question }}">
</form>
{% if messages %}
    {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">{{ message }}</div>
    {% endfor %}
{% endif %}
</div>
</div>
{% endblock %}